services:
  - type: web
    name: telegram-translator-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
    plan: free